apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunsoaked-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sunsoaked-app
  template:
    metadata:
      labels:
        app: sunsoaked-app
    spec:
      containers:
      - name: sunsoaked-container
        image: vaibhavdeshwal/sunsoaked-app:afe2b4b5f39f9e56ce9d6a54fcf0b86e9e9ee9f2
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sunsoaked-service
  namespace: default
spec:
  selector:
    app: sunsoaked-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
