apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunsoaked-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sunsoaked-app
  template:
    metadata:
      labels:
        app: sunsoaked-app
    spec:
      containers:
      - name: sunsoaked-container
        image: vaibhavdeshwal/sunsoaked-app:dc68e4dd30adfe481a5c00bc74eb27967c666186
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sunsoaked-service
  namespace: default
spec:
  selector:
    app: sunsoaked-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
