name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-n-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: vaibhavdeshwal/sunsoaked-app:${{ github.sha }}
 
  update-k8s-manifest:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: k8s

    - name: Update Kubernetes manifest
      run: |
        git branch
        sed -i 's|image: .*/sunsoaked-app:.*|image: vaibhavdeshwal/sunsoaked-app:${{ github.sha }}|' k8s/deployment.yaml

    - name: Push changes
      run: |
        git branch
        git config --global user.name 'vaibhavdeshwal'
        git config --global user.email 'actions@github.com'
        git add k8s/deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:k8s