name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: vaibhavdeshwal/sunsoaked-app:${{ github.sha }}

    - name: Update Kubernetes manifest
      run: |
        sed -i 's|image: .*/sunsoaked-app:.*|image: vaibhavdeshwal/sunsoaked-app:${{ github.sha }}|' k8s/deployment.yaml

    - name: Commit and push changes
      run: |
        git branch
        # git config --global user.name 'vaibhavdeshwal'
        # git config --global user.email 'actions@github.com'
        # git checkout -b k8s || git checkout k8s 
        # git pull origin k8s
        # git add k8s/deployment.yml
        # git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
        # git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:k8s